# Generated by Django 6.0.3 on 2026-03-10 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0002_initial'),
        ('operaciones', '0003_asignacion_evento_incidencia_and_more'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaReasignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(choices=[('MAQUINA_DISPONIBLE', 'Maquina Disponible'), ('OPTIMIZAR_EFICIENCIA', 'Optimizar Eficiencia'), ('CUBRIR_AUSENCIA', 'Cubrir Ausencia'), ('BALANCEAR_CARGA', 'Balancear Carga')], max_length=30)),
                ('descripcion', models.TextField()),
                ('impacto_estimado', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de mejora estimado en produccion', max_digits=5)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('notas_decision', models.TextField(blank=True)),
                ('asignacion_creada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencia_origen', to='operaciones.asignacion')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_decididas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_reasignacion', to='usuarios.empresa')),
                ('maquina_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_entrada', to='maquinas.maquina')),
                ('maquina_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_salida', to='maquinas.maquina')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_reasignacion', to='operaciones.operario')),
            ],
            options={
                'verbose_name': 'Sugerencia de Reasignacion',
                'verbose_name_plural': 'Sugerencias de Reasignacion',
                'db_table': 'sugerencias_reasignacion',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'empresa'], name='sugerencias_estado_ac15ed_idx'), models.Index(fields=['operario', 'estado'], name='sugerencias_operari_1bede3_idx')],
            },
        ),
    ]
