[pytest]
DJANGO_SETTINGS_MODULE = flexop.settings
python_files = tests.py test_*.py *_tests.py
pythonpath = .
testpaths =
    flexop/tests
    operaciones/tests
    usuarios/tests
    metricas/tests
    ordenes/tests
    maquinas/tests
    alertas/tests
    reasignaciones/tests
    reportes/tests
    tests
addopts =
    --reuse-db
    -v
    --strict-markers
    -W ignore::DeprecationWarning:drf_yasg.*
markers =
    django_db: tests que requieren acceso a la base de datos
