# Generated by Django 6.0.3 on 2026-03-10 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('maquinas', '0002_initial'),
        ('operaciones', '0003_asignacion_evento_incidencia_and_more'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='incidencia_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='operaciones.incidencia'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='maquina_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='maquinas.maquina'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='operario_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='operaciones.operario'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='resuelta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='alerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='alertas.alerta'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reglaalerta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_alerta', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='regla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='alertas.reglaalerta'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['estado', 'prioridad'], name='alertas_estado_d7bcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['empresa', 'estado'], name='alertas_empresa_2f80d8_idx'),
        ),
    ]
