# Generated by Django 4.2.30 on 2026-05-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0002_initial'),
        ('alertas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='objetivo_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='metricas.objetivoproduccion'),
        ),
    ]
