# Generated by Django 6.0.3 on 2026-03-10 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0002_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('producto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad', models.CharField(default='unidades', max_length=50)),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(help_text='Fecha y hora limite para completar la orden')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('fecha_despachada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('LISTA', 'Lista para Despacho'), ('DESPACHADA', 'Despachada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='usuarios.empresa')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='maquinas.maquina')),
            ],
            options={
                'verbose_name': 'Orden de Produccion',
                'verbose_name_plural': 'Ordenes de Produccion',
                'db_table': 'ordenes_produccion',
                'ordering': ['-prioridad', 'fecha_limite', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ColaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_COLA', 'En Cola'), ('DESPACHADA', 'Despachada')], default='EN_COLA', max_length=20)),
                ('posicion_manual', models.IntegerField(default=0, help_text='Posicion manual para reordenar la cola')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('despachado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_realizados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cola_despacho', to='usuarios.empresa')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicion_cola', to='ordenes.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Cola de Despacho',
                'verbose_name_plural': 'Cola de Despacho',
                'db_table': 'cola_despacho',
                'ordering': ['-orden__prioridad', 'orden__fecha_limite', 'posicion_manual', 'fecha_entrada'],
            },
        ),
        migrations.AddIndex(
            model_name='ordenproduccion',
            index=models.Index(fields=['estado', 'prioridad'], name='ordenes_pro_estado_232f96_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccion',
            index=models.Index(fields=['empresa', 'estado'], name='ordenes_pro_empresa_f899a8_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccion',
            index=models.Index(fields=['fecha_limite'], name='ordenes_pro_fecha_l_01bf16_idx'),
        ),
    ]
