# Generated by Django 6.0.3 on 2026-03-05 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento exacto del cambio de estado')),
                ('observacion', models.TextField(blank=True, help_text='Motivo o comentarios sobre el cambio de estado')),
            ],
            options={
                'verbose_name': 'Estado de Máquina',
                'verbose_name_plural': 'Estados de Máquina',
                'db_table': 'estados_maquina',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('capacidad_teorica', models.DecimalField(decimal_places=2, help_text='Producción teórica por hora', max_digits=10)),
                ('estado_actual', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OPERANDO', 'Operando'), ('MANTENIMIENTO', 'En Mantenimiento'), ('PARADA', 'Parada'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='DISPONIBLE', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'db_table': 'maquinas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Explicación del tipo de máquina y sus características')),
            ],
            options={
                'verbose_name': 'Tipo de Máquina',
                'verbose_name_plural': 'Tipos de Máquina',
                'db_table': 'tipos_maquina',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadEficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(help_text='Símbolo corto de la unidad (ej: u/h, kg/h)', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Explicación de cuándo usar esta unidad')),
            ],
            options={
                'verbose_name': 'Unidad de Eficiencia',
                'verbose_name_plural': 'Unidades de Eficiencia',
                'db_table': 'unidades_eficiencia',
                'ordering': ['nombre'],
            },
        ),
    ]
