# Generated by Django 6.0.3 on 2026-03-05 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadomaquina',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maquina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='estadomaquina',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='maquinas.maquina'),
        ),
        migrations.AddField(
            model_name='tipomaquina',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_maquina', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='maquinas.tipomaquina'),
        ),
        migrations.AddField(
            model_name='unidadeficiencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_eficiencia', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='unidad_capacidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='maquinas.unidadeficiencia'),
        ),
        migrations.AddIndex(
            model_name='estadomaquina',
            index=models.Index(fields=['maquina', 'fecha_hora'], name='estados_maq_maquina_cdd152_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadeficiencia',
            unique_together={('nombre', 'empresa')},
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['estado_actual'], name='maquinas_estado__992370_idx'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['empresa', 'activa'], name='maquinas_empresa_c1d81f_idx'),
        ),
    ]
