# Generated by Django 4.2.30 on 2026-05-28 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
