# Generated by Django 6.0.3 on 2026-03-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'db_table': 'habilidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=50, unique=True)),
                ('fecha_contratacion', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('eficiencia_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Eficiencia promedio histórica (%)', max_digits=5)),
                ('total_tareas_completadas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Operario',
                'verbose_name_plural': 'Operarios',
                'db_table': 'operarios',
                'ordering': ['codigo_empleado'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno (ej: 06:00)')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del turno (ej: 14:00)')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no se puede asignar a operarios')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['hora_inicio'],
            },
        ),
    ]
