# Generated by Django 6.0.3 on 2026-03-05 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0002_initial'),
        ('operaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='habilidad',
            name='tipos_maquina',
            field=models.ManyToManyField(blank=True, help_text='Tipos de máquinas que requieren esta habilidad', related_name='habilidades_requeridas', to='maquinas.tipomaquina'),
        ),
        migrations.AddField(
            model_name='operario',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='operarios', to='operaciones.habilidad'),
        ),
        migrations.AddField(
            model_name='operario',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'rol': 'OPERARIO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_operario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='operario',
            name='turno_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operarios_asignados', to='operaciones.turno'),
        ),
        migrations.AlterUniqueTogether(
            name='habilidad',
            unique_together={('nombre', 'empresa')},
        ),
    ]
