# Generated by Django 6.0.3 on 2026-03-10 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_initial'),
        ('operaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha para la cual se crea esta asignacion')),
                ('hora_inicio_real', models.DateTimeField(blank=True, help_text='Momento exacto en que el operario inicio la tarea', null=True)),
                ('hora_fin_real', models.DateTimeField(blank=True, help_text='Momento exacto en que el operario termino la tarea', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='maquinas.maquina')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='operaciones.operario')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='operaciones.turno')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'asignaciones',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INICIO', 'Inicio de Tarea'), ('FIN', 'Fin de Tarea'), ('PAUSA', 'Pausa'), ('REANUDACION', 'Reanudacion'), ('CAMBIO_MAQUINA', 'Cambio de Maquina'), ('INCIDENCIA', 'Incidencia Reportada')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('datos_json', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON', null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='operaciones.asignacion')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FALLA_MAQUINA', 'Falla de Maquina'), ('FALTA_MATERIAL', 'Falta de Material'), ('PROBLEMA_CALIDAD', 'Problema de Calidad'), ('OTRO', 'Otro')], max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En Proceso'), ('RESUELTA', 'Resuelta'), ('ESCALADA', 'Escalada')], default='ABIERTA', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='operaciones.asignacion')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='maquinas.maquina')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencias',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['fecha', 'estado'], name='asignacione_fecha_755525_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['operario', 'fecha'], name='asignacione_operari_e6f2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['maquina', 'fecha'], name='asignacione_maquina_3f1e28_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['asignacion', 'tipo'], name='eventos_asignac_fa2f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_hora'], name='eventos_fecha_h_9b3754_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado', 'prioridad'], name='incidencias_estado_c44565_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['maquina', 'fecha_reporte'], name='incidencias_maquina_49f577_idx'),
        ),
    ]
