# Generated by Django 6.0.3 on 2026-03-10 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaEficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('produccion_real', models.DecimalField(decimal_places=2, help_text='Total producido', max_digits=12)),
                ('produccion_teorica', models.DecimalField(decimal_places=2, help_text='Produccion esperada segun capacidad de maquina', max_digits=12)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, help_text='Horas efectivas de trabajo', max_digits=6)),
                ('eficiencia_calculada', models.DecimalField(decimal_places=2, help_text='Porcentaje de eficiencia (100 = 100%)', max_digits=6)),
            ],
            options={
                'verbose_name': 'Metrica de Eficiencia',
                'verbose_name_plural': 'Metricas de Eficiencia',
                'db_table': 'metricas_eficiencia',
                'ordering': ['-fecha', '-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('POR_MAQUINA', 'Por Maquina'), ('POR_TURNO', 'Por Turno'), ('POR_OPERARIO', 'Por Operario')], max_length=20)),
                ('cantidad_objetivo', models.DecimalField(decimal_places=2, help_text='Cantidad a producir como meta', max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Objetivo de Produccion',
                'verbose_name_plural': 'Objetivos de Produccion',
                'db_table': 'objetivos_produccion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad producida en la unidad de la maquina', max_digits=12)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de Produccion',
                'verbose_name_plural': 'Registros de Produccion',
                'db_table': 'registros_produccion',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
