# Generated by Django 6.0.3 on 2026-03-10 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0002_initial'),
        ('metricas', '0001_initial'),
        ('operaciones', '0003_asignacion_evento_incidencia_and_more'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metricaeficiencia',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metricas_eficiencia', to='operaciones.asignacion'),
        ),
        migrations.AddField(
            model_name='metricaeficiencia',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_eficiencia', to='maquinas.maquina'),
        ),
        migrations.AddField(
            model_name='metricaeficiencia',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_eficiencia', to='operaciones.operario'),
        ),
        migrations.AddField(
            model_name='objetivoproduccion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_produccion', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='objetivoproduccion',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='maquinas.maquina'),
        ),
        migrations.AddField(
            model_name='objetivoproduccion',
            name='operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='operaciones.operario'),
        ),
        migrations.AddField(
            model_name='objetivoproduccion',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='operaciones.turno'),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_produccion', to='operaciones.asignacion'),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_produccion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='metricaeficiencia',
            index=models.Index(fields=['operario', 'fecha'], name='metricas_ef_operari_9a882c_idx'),
        ),
        migrations.AddIndex(
            model_name='metricaeficiencia',
            index=models.Index(fields=['maquina', 'fecha'], name='metricas_ef_maquina_fe92b1_idx'),
        ),
        migrations.AddIndex(
            model_name='registroproduccion',
            index=models.Index(fields=['asignacion', 'fecha_hora'], name='registros_p_asignac_e5cef8_idx'),
        ),
    ]
